#Do not touch me
_version: 1

#H2 is a special db since it does not rely on a server, but on a single file
db:
  #Allowed values: H2, MariaDB, SQLite
  provider: H2
  #Database credential
  username: root
  password: root
  #defaults: localhost (127.0.0.1 for nerds)
  url: localhost
  #leave blank (or put it <1) to use the default port
  port: 0
  #Database name
  name: main
  #The prefix to add to each table name
  prefix: teams_

name:
  block:
    - "fuck"
    - "sex"
    - "banned"
    - "block"
    - "blocca"
    #To prevent SQL injections
    - "'"
teams:
  #Maxium players a team can have. Must be >2
  #Default 20
  max-player: 25